"""Added review model

Revision ID: 12241aac0302
Revises: 
Create Date: 2024-04-03 22:32:08.802740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12241aac0302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'price',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
